---
development:
  dialect: "sqlite3"
  database: ./fortihoney_fortihoney_development.sqlite

test:
  dialect: "sqlite3"
  database: ./fortihoney_fortihoney_test.sqlite

production:
  dialect: "sqlite3"
  database: ./fortihoney_fortihoney_production.sqlite
